version: "3.9"
services:
  redis-master:
    image: redis:8
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./ops/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    hostname: redis-master
    container_name: redis-master
  redis-replica:
    image: redis:8
    depends_on:
      - redis-master
    command: ["sh", "-c", "sleep 1 && redis-server --replicaof redis-master 6379 --port 6379"]
    volumes:
      - ./ops/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
  sentinel1:
    image: redis:8
    depends_on:
      - redis-master
      - redis-replica
    environment:
      - SKIP_FIX_PERMS=1
    volumes:
      - ./ops/redis/start-sentinel.sh:/usr/local/bin/start-sentinel.sh:ro
    command: ["/usr/local/bin/start-sentinel.sh"]
    ports:
      - "26379:26379"
  sentinel2:
    image: redis:8
    depends_on:
      - redis-master
      - redis-replica
    environment:
      - SKIP_FIX_PERMS=1
    volumes:
      - ./ops/redis/start-sentinel.sh:/usr/local/bin/start-sentinel.sh:ro
    command: ["/usr/local/bin/start-sentinel.sh"]
    ports:
      - "26380:26379"
  sentinel3:
    image: redis:8
    depends_on:
      - redis-master
      - redis-replica
    environment:
      - SKIP_FIX_PERMS=1
    volumes:
      - ./ops/redis/start-sentinel.sh:/usr/local/bin/start-sentinel.sh:ro
    command: ["/usr/local/bin/start-sentinel.sh"]
    ports:
      - "26381:26379"
