# Generated by Django 5.1.15 on 2026-05-04 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0006_increase_area_ha_precision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vaccination", "Vaccination"),
                            ("fertilizer", "Fertilizer"),
                            ("irrigation", "Irrigation"),
                            ("ndvi_trigger", "NDVI Trigger"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("next_due_at", models.DateTimeField(db_index=True)),
                (
                    "last_executed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("none", "One-time"),
                            ("interval", "Interval"),
                            ("cron", "Cron (future)"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="farms.farm",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_due_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_due_at"],
                        name="activity_status_due_idx",
                    ),
                    models.Index(
                        fields=["owner", "status", "next_due_at"],
                        name="activity_owner_status_idx",
                    ),
                    models.Index(
                        fields=["farm", "status", "next_due_at"],
                        name="activity_farm_status_idx",
                    ),
                ],
            },
        ),
    ]
