# Generated by Django 5.1.15 on 2026-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_execution_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="cron_expression",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "One-time"),
                    ("interval", "Interval"),
                    ("cron", "Cron"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
