# Generated by Django 5.1.15 on 2026-06-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("feed_url", models.URLField()),
                ("image_url", models.URLField(blank=True)),
                ("language", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_refreshed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_refresh_status",
                    models.CharField(
                        blank=True,
                        help_text='Outcome of the most recent ingestion: "ok", "error", or "" (never refreshed).',
                        max_length=20,
                    ),
                ),
                ("last_refresh_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
                "db_table": "podcasts_podcast",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("audio_url", models.URLField()),
                (
                    "audio_mime_type",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="podcasts.podcast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast episode",
                "verbose_name_plural": "Podcast episodes",
                "db_table": "podcasts_episode",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["podcast", "-published_at"],
                        name="podcasts_ep_podcast_7dabdb_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("podcast", "guid"),
                        name="podcasts_episode_podcast_guid_unique",
                    )
                ],
            },
        ),
    ]
