"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
import os
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass
from datetime import timedelta
from pathlib import Path
from typing import Any, cast
from urllib.parse import parse_qs, quote, urlparse

import dj_database_url
import environ
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from redis.connection import URL_QUERY_ARGUMENT_PARSERS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
env.read_env(BASE_DIR / ".env")
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")
DJANGO_ENV = env(
    "DJANGO_ENV", default="development"
)  # development|ci|staging|production
IS_PROD = DJANGO_ENV == "production"
REQUIRE_SECRETS = DJANGO_ENV in {"production", "staging"}
IS_TESTING = (
    "PYTEST_CURRENT_TEST" in os.environ
    or "pytest" in sys.argv[0]
    or "test" in sys.argv
)

DJANGO_DB_LOG_LEVEL = env.str("DJANGO_DB_LOG_LEVEL", default="WARNING").upper()


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS: list[str] = cast(
    list[str],
    env.list(
        "DJANGO_ALLOWED_HOSTS",
        default=["localhost", "127.0.0.1"],
    ),
)
CORS_ALLOWED_ORIGINS: list[str] = cast(
    list[str], env.list("DJANGO_CORS_ALLOWED_ORIGINS", default=[])
)
API_KEY_THROTTLE_RATE = env("API_KEY_THROTTLE_RATE", default="500/min")
API_KEY_AUTH_LOG_SUCCESS = env.bool("API_KEY_AUTH_LOG_SUCCESS", default=True)
API_KEY_AUTH_CACHE_TTL_SECONDS = env.int(
    "API_KEY_AUTH_CACHE_TTL_SECONDS", default=60
)
API_KEY_AUTH_CACHE_ALIAS = env("API_KEY_AUTH_CACHE_ALIAS", default="default")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_prometheus",
    "django_extensions",
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt",
    "accounts",
    "api_keys",
    "integrations",
    "farms",
    "ndvi",
    "weather",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "django.log"),
            "formatter": "verbose",
        },
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "root": {"handlers": ["console", "file"], "level": "DEBUG"},
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "farms": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "httpx": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "httpcore": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console", "file"],
            "level": DJANGO_DB_LOG_LEVEL,
            "propagate": False,
        },
    },
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# --- Database ---
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=IS_PROD,
    )
}

# --- Prometheus DB instrumentation ---
_engine = DATABASES["default"].get("ENGINE")
if _engine == "django.db.backends.postgresql":
    DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"
elif _engine == "django.db.backends.postgresql_psycopg2":
    DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.postgresql"
elif _engine == "django.db.backends.mysql":
    DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.mysql"
elif _engine == "django.db.backends.sqlite3":
    # optional:
    # DATABASES["default"]["ENGINE"] = "django_prometheus.db.backends.sqlite3"
    pass

# --- MySQL specific tuning ---
if DATABASES["default"].get("ENGINE") in {
    "django.db.backends.mysql",
    "django_prometheus.db.backends.mysql",
}:
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].update(
        {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES',"
            "time_zone='+00:00'",
            "charset": "utf8mb4",
            "use_unicode": True,
        }
    )
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# --- Pytest: in-memory SQLite ---
if IS_TESTING:
    DATABASES = {
        # keep plain sqlite OR switch to django_prometheus.db.backends.sqlite3
        # (optional)
        "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}
    }


# Caches helpers


@dataclass(frozen=True)
class RedisSentinelConfig:
    service_name: str
    sentinels: tuple[tuple[str, int], ...]
    db: int
    username: str | None = None
    password: str | None = None
    sentinel_kwargs: dict[str, Any] | None = None


def _split_host_port(raw: str) -> tuple[str, int]:
    raw = raw.strip()
    if raw.startswith("["):
        match = re.match(r"\[(?P<host>[^\]]+)\](?::(?P<port>\d+))?$", raw)
        if not match:
            raise ImproperlyConfigured(f"Invalid sentinel address '{raw}'")
        host = match.group("host")
        port = match.group("port") or "26379"
    else:
        if ":" in raw:
            host, port = raw.split(":", 1)
        else:
            host, port = raw, "26379"
    try:
        return host, int(port)
    except ValueError as exc:
        raise ImproperlyConfigured(
            f"Invalid sentinel port in '{raw}'"
        ) from exc


def _parse_redis_sentinel_url(
    value: str, service_name_override: str | None = None
) -> tuple[str, RedisSentinelConfig]:
    parsed = urlparse(value)
    if parsed.scheme != "redis-sentinel":
        raise ImproperlyConfigured("Expected redis-sentinel scheme")

    if "@" in parsed.netloc:
        _, host_segment = parsed.netloc.split("@", 1)
    else:
        host_segment = parsed.netloc

    sentinel_hosts = tuple(
        _split_host_port(part)
        for part in re.split(r"[;,]", host_segment)
        if part.strip()
    )
    if not sentinel_hosts:
        raise ImproperlyConfigured("No sentinel hosts provided")

    query = parse_qs(parsed.query or "")
    service_name = (
        query.pop("service_name", [None])[0]
        or query.pop("master_name", [None])[0]
        or service_name_override
    )
    if not service_name:
        raise ImproperlyConfigured(
            "Redis sentinel URL is missing service_name"
        )

    db_value_raw = query.pop("db", [None])[0]
    db_value: int
    if db_value_raw is None:
        if parsed.path and parsed.path not in ("/", ""):
            try:
                db_value = int(parsed.path.lstrip("/"))
            except ValueError as exc:
                raise ImproperlyConfigured("Invalid redis DB in path") from exc
        else:
            db_value = 0
    else:
        try:
            db_value = int(db_value_raw)
        except ValueError as exc:
            raise ImproperlyConfigured("Invalid redis DB value") from exc

    password = parsed.password or query.pop("password", [None])[0]
    username = parsed.username or query.pop("username", [None])[0]

    sentinel_kwargs: dict[str, Any] = {}
    for key, values in list(query.items()):
        if not values:
            continue
        value = values[0]
        parser = URL_QUERY_ARGUMENT_PARSERS.get(key)
        if parser:
            parsed_value = cast(Callable[[str], Any], parser)(value)
        else:
            parsed_value = value
        if key.startswith("sentinel_"):
            sentinel_kwargs[key[len("sentinel_") :]] = parsed_value
        elif key in {
            "socket_timeout",
            "socket_connect_timeout",
            "socket_keepalive",
            "socket_keepalive_options",
        }:
            sentinel_kwargs[key] = parsed_value

    final_sentinel_kwargs = sentinel_kwargs or None
    location = f"redis://{service_name}/{db_value}"
    return (
        location,
        RedisSentinelConfig(
            service_name=service_name,
            sentinels=sentinel_hosts,
            db=db_value,
            username=username,
            password=password,
            sentinel_kwargs=final_sentinel_kwargs,
        ),
    )


def _parse_cache_url(value: str) -> tuple[str, RedisSentinelConfig | None]:
    if value.startswith("redis-sentinel://"):
        return _parse_redis_sentinel_url(value)
    return value, None


def _redis_cache(
    location: str, sentinel_config: RedisSentinelConfig | None = None
) -> dict[str, Any]:
    options: dict[str, Any] = {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
    }
    if sentinel_config:
        options.update(
            {
                "CLIENT_CLASS": "django_redis.client.SentinelClient",
                "CONNECTION_FACTORY": (
                    "django_redis.pool.SentinelConnectionFactory"
                ),
                "SENTINELS": list(sentinel_config.sentinels),
            }
        )
        if sentinel_config.password:
            options["PASSWORD"] = sentinel_config.password
        if sentinel_config.username:
            options["USERNAME"] = sentinel_config.username
        if sentinel_config.sentinel_kwargs:
            options["SENTINEL_KWARGS"] = sentinel_config.sentinel_kwargs

    return {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": location,
        "OPTIONS": options,
    }


def _parse_transport_options(
    raw: str | None, setting_name: str
) -> dict[str, Any]:
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ImproperlyConfigured(
            f"{setting_name} must be valid JSON"
        ) from exc
    if not isinstance(parsed, dict):
        raise ImproperlyConfigured(f"{setting_name} must be a JSON object")
    return cast(dict[str, Any], parsed)


def _redis_sentinel_to_celery_url(
    sentinel_config: RedisSentinelConfig,
) -> str:
    credentials = ""
    if sentinel_config.username is not None:
        credentials = quote(sentinel_config.username, safe="")
        if sentinel_config.password is not None:
            credentials += f":{quote(sentinel_config.password, safe='')}"
        credentials += "@"
    elif sentinel_config.password is not None:
        credentials = f":{quote(sentinel_config.password, safe='')}@"

    return ";".join(
        f"sentinel://{credentials}{host}:{port}/{sentinel_config.db}"
        for host, port in sentinel_config.sentinels
    )


def _parse_celery_redis_url(
    value: str,
    transport_options_raw: str | None,
    transport_setting_name: str,
) -> tuple[str, dict[str, Any]]:
    transport_options = _parse_transport_options(
        transport_options_raw, transport_setting_name
    )
    if not value.startswith("redis-sentinel://"):
        return value, transport_options

    _, sentinel_config = _parse_redis_sentinel_url(value)
    sentinel_transport_options: dict[str, Any] = {
        "master_name": sentinel_config.service_name,
    }
    if sentinel_config.sentinel_kwargs:
        sentinel_transport_options["sentinel_kwargs"] = (
            sentinel_config.sentinel_kwargs
        )
    sentinel_transport_options.update(transport_options)
    return (
        _redis_sentinel_to_celery_url(sentinel_config),
        sentinel_transport_options,
    )


REDIS_URL_RAW = env("REDIS_URL", default=None)
REDIS_SENTINEL_CONFIG: RedisSentinelConfig | None = None
REDIS_URL: str | None = None

if REDIS_URL_RAW:
    REDIS_URL, REDIS_SENTINEL_CONFIG = _parse_cache_url(REDIS_URL_RAW)
else:
    REDIS_URL = None

if REDIS_URL:
    default_cache_config = _redis_cache(
        REDIS_URL, sentinel_config=REDIS_SENTINEL_CONFIG
    )
    throttle_cache_config = dict(default_cache_config)
else:
    default_cache_config = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default",
    }
    throttle_cache_config = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "throttle",
    }

if IS_TESTING:
    default_cache_config = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default",
    }
    throttle_cache_config = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "throttle",
    }

if IS_PROD and not REDIS_URL:
    raise ImproperlyConfigured("Set REDIS_URL for production caching")

CACHES = {
    "default": default_cache_config,
    "throttle": throttle_cache_config,
}

DJANGO_REDIS_IGNORE_EXCEPTIONS = not IS_PROD


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

FRONTEND_RESET_URL = env("FRONTEND_RESET_URL", default="")

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", default="localhost")
EMAIL_PORT = env.int("EMAIL_PORT", default=25)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="no-reply@localhost")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "api_keys.authentication.ApiKeyAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "api_keys.throttling.ApiKeyRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/min",
        "user": "1000/min",
        "register": "5/min",
        "login": "10/min",
        "token_refresh": "20/min",
        "password_reset": "5/min",
        "password_reset_confirm": "10/min",
        "api_key": env("API_KEY_THROTTLE_RATE", default="10/min"),
        "nextcloud_hmac": env("API_KEY_THROTTLE_RATE", default="10/min"),
    },
    "EXCEPTION_HANDLER": "config.api.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

AUTHENTICATION_BACKENDS = [
    "accounts.auth_backends.UsernameOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env.int("SIMPLE_JWT_ACCESS_MINUTES", default=15)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env.int("SIMPLE_JWT_REFRESH_DAYS", default=7)
    ),
    "ISSUER": env("SIMPLE_JWT_ISSUER", default="weather-apis"),
    "AUDIENCE": env("SIMPLE_JWT_AUDIENCE", default="nextcloud"),
}

INTEGRATION_JWT_ACCESS_MINUTES = env.int(
    "INTEGRATION_JWT_ACCESS_MINUTES",
    default=5,
)

DJANGO_API_KEY_PEPPER = env("DJANGO_API_KEY_PEPPER", default=None)

if DJANGO_API_KEY_PEPPER is None:
    if REQUIRE_SECRETS:
        raise ImproperlyConfigured(
            "Set the DJANGO_API_KEY_PEPPER environment variable"
        )
    # dev/ci/tests default (not a real secret)
    DJANGO_API_KEY_PEPPER = "dev-pepper"

# Nextcloud request signing (HMAC)
NEXTCLOUD_HMAC_ENABLED = env.bool("NEXTCLOUD_HMAC_ENABLED", default=True)
NEXTCLOUD_HMAC_MAX_SKEW_SECONDS = env.int(
    "NEXTCLOUD_HMAC_MAX_SKEW_SECONDS",
    default=300,
)
NEXTCLOUD_HMAC_NONCE_TTL_SECONDS = env.int(
    "NEXTCLOUD_HMAC_NONCE_TTL_SECONDS",
    default=360,
)
NEXTCLOUD_HMAC_CACHE_ALIAS = env(
    "NEXTCLOUD_HMAC_CACHE_ALIAS", default="default"
)
NEXTCLOUD_HMAC_DEBUG_LOGGING = env.bool(
    "NEXTCLOUD_HMAC_DEBUG_LOGGING",
    default=False,
)

INTEGRATION_LEGACY_CONFIG_ALLOWED = env.bool(
    "INTEGRATION_LEGACY_CONFIG_ALLOWED",
    default=False,
)
INTEGRATION_HMAC_CLIENTS_JSON = env(
    "INTEGRATION_HMAC_CLIENTS_JSON", default=""
)

# HMAC secret rotation overlap window (seconds).
# Default: 72 hours to allow propagation while limiting exposure if a secret
# leaks.
INTEGRATIONS_HMAC_PREVIOUS_TTL_SECONDS = env.int(
    "INTEGRATIONS_HMAC_PREVIOUS_TTL_SECONDS",
    default=259200,
)

if NEXTCLOUD_HMAC_CACHE_ALIAS not in CACHES:  # pragma: no cover
    raise ImproperlyConfigured(
        "NEXTCLOUD_HMAC_CACHE_ALIAS must be one of: "
        f"{', '.join(CACHES.keys())}"
    )
if API_KEY_AUTH_CACHE_ALIAS not in CACHES:  # pragma: no cover
    raise ImproperlyConfigured(
        f"API_KEY_AUTH_CACHE_ALIAS must be one of: {', '.join(CACHES.keys())}"
    )

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SPECTACULAR_SETTINGS = {
    "TITLE": "Weather APIs",
    "DESCRIPTION": "REST API for user authentication and "
    "API key lifecycle management.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "POSTPROCESSING_HOOKS": [
        "config.api.openapi.remove_deprecated_integration_aliases",
    ],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            },
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key",
            },
        },
    },
    "ENUM_NAME_OVERRIDES": {
        "ApiKeyScopeEnum": "api_keys.models.ApiKeyScope",
        "ApiKeyScopeValueEnum": ("read", "write", "admin"),
    },
}


REST_FRAMEWORK = cast(dict[str, Any], REST_FRAMEWORK)

if IS_TESTING:
    disable_throttle = env.bool(
        "DISABLE_THROTTLE_IN_TESTS",
        default=False,
    )
    if disable_throttle:
        REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []

# NDVI defaults and limits
NDVI_ENGINE = env("NDVI_ENGINE", default="sentinelhub")
NDVI_QUEUE_BACKEND = env("NDVI_QUEUE_BACKEND", default="celery")
NDVI_MAX_AREA_KM2 = env.float("NDVI_MAX_AREA_KM2", default=5000.0)
NDVI_MAX_DATERANGE_DAYS = env.int("NDVI_MAX_DATERANGE_DAYS", default=370)
NDVI_LOCK_TIMEOUT_SECONDS = env.int("NDVI_LOCK_TIMEOUT_SECONDS", default=300)
NDVI_CACHE_TTL_TIMESERIES_SECONDS = env.int(
    "NDVI_CACHE_TTL_TIMESERIES_SECONDS",
    default=86400,
)
NDVI_CACHE_TTL_LATEST_SECONDS = env.int(
    "NDVI_CACHE_TTL_LATEST_SECONDS",
    default=21600,
)
NDVI_DEFAULT_STEP_DAYS = env.int("NDVI_DEFAULT_STEP_DAYS", default=7)
NDVI_DEFAULT_MAX_CLOUD = env.int("NDVI_DEFAULT_MAX_CLOUD", default=30)
NDVI_DEFAULT_LOOKBACK_DAYS = env.int("NDVI_DEFAULT_LOOKBACK_DAYS", default=14)
NDVI_STAC_API_URL = env(
    "NDVI_STAC_API_URL",
    default="https://stac.dataspace.copernicus.eu/v1/",
)
NDVI_STAC_COLLECTION = env(
    "NDVI_STAC_COLLECTION",
    default="sentinel-2-l2a",
)
NDVI_STAC_MAX_CLOUD_DEFAULT = env.int(
    "NDVI_STAC_MAX_CLOUD_DEFAULT",
    default=30,
)
NDVI_STAC_DATE_WINDOW_DAYS = env.int(
    "NDVI_STAC_DATE_WINDOW_DAYS",
    default=3,
)
NDVI_STAC_ASSET_RED = env("NDVI_STAC_ASSET_RED", default="B04_10m")
NDVI_STAC_ASSET_NIR = env("NDVI_STAC_ASSET_NIR", default="B08_10m")
NDVI_STAC_TIMEOUT_SECS = env.float(
    "NDVI_STAC_TIMEOUT_SECS",
    default=30,
)

# STAC API request throttling (prevent WAF blocks)
NDVI_STAC_REQUEST_INTERVAL_SECS = env.float(
    "NDVI_STAC_REQUEST_INTERVAL_SECS",
    default=10.0,  # Min seconds between requests
)
NDVI_STAC_JITTER_MIN_SECS = env.float(
    "NDVI_STAC_JITTER_MIN_SECS",
    default=1.0,  # Min jitter in seconds
)
NDVI_STAC_JITTER_MAX_SECS = env.float(
    "NDVI_STAC_JITTER_MAX_SECS",
    default=5.0,  # Max jitter in seconds
)

NDVI_MANUAL_REFRESH_COOLDOWN_SECONDS = env.int(
    "NDVI_MANUAL_REFRESH_COOLDOWN_SECONDS",
    default=900,
)
NDVI_REQUEST_TIMEOUT_SECONDS = env.float(
    "NDVI_REQUEST_TIMEOUT_SECONDS",
    default=20,
)
NDVI_RASTER_ENGINE_PATH = env(
    "NDVI_RASTER_ENGINE_PATH",
    default="ndvi.raster.sentinelhub_engine.SentinelHubRasterEngine",
)
NDVI_RASTER_ENGINE_NAME = env(
    "NDVI_RASTER_ENGINE_NAME",
    default=NDVI_ENGINE,
)
NDVI_RASTER_MAX_SIZE = env.int("NDVI_RASTER_MAX_SIZE", default=1024)
NDVI_RASTER_DEFAULT_SIZE = env.int(
    "NDVI_RASTER_DEFAULT_SIZE",
    default=512,
)
NDVI_RASTER_MANUAL_QUEUE_COOLDOWN_SECONDS = env.int(
    "NDVI_RASTER_MANUAL_QUEUE_COOLDOWN_SECONDS",
    default=900,
)
NDVI_RASTER_CACHE_TTL_SECONDS = env.int(
    "NDVI_RASTER_CACHE_TTL_SECONDS",
    default=86400,
)

# Internal proxy routing to Rust microservices.
NDVI_SERVICE_URL = env("NDVI_SERVICE_URL", default="")
NDVI_PROXY_ENABLED = env.bool(
    "NDVI_PROXY_ENABLED", default=bool(NDVI_SERVICE_URL)
)
WEATHER_SERVICE_URL = env("WEATHER_SERVICE_URL", default="")
WEATHER_PROXY_ENABLED = env.bool(
    "WEATHER_PROXY_ENABLED", default=bool(WEATHER_SERVICE_URL)
)
PROXY_TIMEOUT_SECONDS = env.float("PROXY_TIMEOUT_SECONDS", default=10.0)

# Weather defaults
WEATHER_PROVIDER_DEFAULT = env(
    "WEATHER_PROVIDER_DEFAULT",
    default="open_meteo",
)
WEATHER_DEFAULT_TZ = env(
    "WEATHER_DEFAULT_TZ",
    default="Africa/Nairobi",
)
OPEN_METEO_BASE_URL = env(
    "OPEN_METEO_BASE_URL",
    default="https://api.open-meteo.com/v1/forecast",
)
NASA_POWER_BASE_URL = env(
    "NASA_POWER_BASE_URL",
    default="https://power.larc.nasa.gov/api/temporal/daily/point",
)
NASA_POWER_DAILY_LAG_DAYS = env.int(
    "NASA_POWER_DAILY_LAG_DAYS",
    default=2,
)
WEATHER_CACHE_TTL_CURRENT_S = env.int(
    "WEATHER_CACHE_TTL_CURRENT_S",
    default=120,
)
WEATHER_CACHE_TTL_DAILY_S = env.int(
    "WEATHER_CACHE_TTL_DAILY_S",
    default=900,
)
WEATHER_CACHE_TTL_WEEKLY_S = env.int(
    "WEATHER_CACHE_TTL_WEEKLY_S",
    default=1800,
)
WEATHER_MAX_RANGE_DAYS = env.int(
    "WEATHER_MAX_RANGE_DAYS",
    default=366,
)
SCHEMA_CACHE_TTL_SECONDS = env.int(
    "SCHEMA_CACHE_TTL_SECONDS",
    default=3600,
)
SCHEMA_CACHE_WARM_INTERVAL_SECONDS = env.int(
    "SCHEMA_CACHE_WARM_INTERVAL_SECONDS",
    default=3300,
)

# Celery
CELERY_BROKER_URL_RAW = env(
    "CELERY_BROKER_URL", default=REDIS_URL_RAW or REDIS_URL or "memory://"
)
CELERY_BROKER_URL, CELERY_BROKER_TRANSPORT_OPTIONS = _parse_celery_redis_url(
    CELERY_BROKER_URL_RAW,
    env("CELERY_BROKER_TRANSPORT_OPTIONS", default=None),
    "CELERY_BROKER_TRANSPORT_OPTIONS",
)
CELERY_RESULT_BACKEND_RAW = env(
    "CELERY_RESULT_BACKEND",
    default="cache+memory://",
)
CELERY_RESULT_BACKEND, CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = (
    _parse_celery_redis_url(
        CELERY_RESULT_BACKEND_RAW,
        env("CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS", default=None),
        "CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS",
    )
)
# Celery's URL properties prefer process env vars over Django settings, so keep
# the translated URLs in sync after reading the raw `.env` values.
os.environ["CELERY_BROKER_URL"] = CELERY_BROKER_URL
os.environ.setdefault("CELERY_BROKER_READ_URL", CELERY_BROKER_URL)
os.environ.setdefault("CELERY_BROKER_WRITE_URL", CELERY_BROKER_URL)
os.environ["CELERY_RESULT_BACKEND"] = CELERY_RESULT_BACKEND
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ALWAYS_EAGER = env.bool(
    "CELERY_TASK_ALWAYS_EAGER",
    default=IS_TESTING,
)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BEAT_SCHEDULE = {
    "ndvi-daily-refresh": {
        "task": "ndvi.tasks.enqueue_daily_refresh",
        "schedule": crontab(hour=3, minute=15),
    },
    "farm-state-daily-coverage": {
        "task": "ndvi.tasks.enqueue_daily_farm_state_coverage",
        "schedule": crontab(hour=3, minute=45),
    },
    "ndvi-weekly-gap-fill": {
        "task": "ndvi.tasks.enqueue_weekly_gap_fill",
        "schedule": crontab(hour=4, minute=0, day_of_week="sun"),
    },
    "schema-cache-warm": {
        "task": "weather.tasks.warm_openapi_schema_cache",
        "schedule": SCHEMA_CACHE_WARM_INTERVAL_SECONDS,
    },
}
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = "Africa/Nairobi"
