from django.urls import path

from radio import views

urlpatterns = [
    path(
        "radio/stations/", views.StationListView.as_view(), name="station-list"
    ),
    path(
        "radio/stations/<str:station_id>/",
        views.StationDetailView.as_view(),
        name="station-detail",
    ),
    path(
        "radio/stations/<str:station_id>/stream/signed/",
        views.SignedStreamView.as_view(),
        name="station-stream-signed",
    ),
    path(
        "radio/stations/<str:station_id>/stream/",
        views.StationStreamView.as_view(),
        name="station-stream",
    ),
    path(
        "radio/stations/<str:station_id>/health/",
        views.StationHealthHistoryView.as_view(),
        name="station-health-history",
    ),
    path(
        "radio/stations/<str:station_id>/now-playing/",
        views.StationNowPlayingView.as_view(),
        name="station-now-playing",
    ),
    path(
        "radio/stations/<str:station_id>/analytics/",
        views.StationAnalyticsView.as_view(),
        name="station-analytics",
    ),
    path(
        "radio/providers/",
        views.ProviderListView.as_view(),
        name="provider-list",
    ),
    path(
        "radio/health/",
        views.RadioHealthView.as_view(),
        name="radio-health",
    ),
    path(
        "radio/favorites/",
        views.FavoriteListCreateView.as_view(),
        name="radio-favorites",
    ),
    path(
        "radio/favorites/<str:station_id>/",
        views.FavoriteDeleteView.as_view(),
        name="radio-favorites-delete",
    ),
    path(
        "radio/history/",
        views.ListeningHistoryListView.as_view(),
        name="radio-history",
    ),
    path(
        "radio/history/recent/",
        views.ListeningHistoryRecentView.as_view(),
        name="radio-history-recent",
    ),
    path(
        "radio/history/<int:session_id>/stop/",
        views.ListeningSessionStopView.as_view(),
        name="radio-history-stop",
    ),
    path(
        "radio/emergency/current/",
        views.EmergencyCurrentView.as_view(),
        name="radio-emergency-current",
    ),
    path(
        "radio/emergency/history/",
        views.EmergencyHistoryView.as_view(),
        name="radio-emergency-history",
    ),
    path(
        "radio/emergency/",
        views.EmergencyCreateView.as_view(),
        name="radio-emergency-create",
    ),
    path(
        "radio/emergency/<int:pk>/",
        views.EmergencyDetailView.as_view(),
        name="radio-emergency-detail",
    ),
    path(
        "radio/tts/",
        views.TTSSynthesizeView.as_view(),
        name="radio-tts",
    ),
]
