# Generated by Django 5.1.15 on 2026-05-12 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("website_url", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "db_table": "radio_provider",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("stream_url", models.URLField()),
                ("format", models.CharField(default="MP3", max_length=20)),
                ("bitrate", models.IntegerField(default=128)),
                ("logo_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stations",
                        to="radio.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
                "db_table": "radio_station",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"],
                        name="radio_stati_is_acti_1d529f_idx",
                    ),
                    models.Index(
                        fields=["provider"],
                        name="radio_stati_provide_bedc51_idx",
                    ),
                    models.Index(
                        fields=["genre"], name="radio_stati_genre_450c05_idx"
                    ),
                ],
            },
        ),
    ]
