# Generated by Django 5.1.15 on 2026-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="api_endpoint",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="api_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="provider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("broadcaster", "Direct Broadcaster"),
                    ("aggregator", "Station Aggregator"),
                    ("api_based", "API-driven"),
                ],
                default="broadcaster",
                max_length=20,
            ),
        ),
    ]
