# Generated by Django 5.1.15 on 2026-06-07 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0004_favorite_listeninghistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyBroadcast",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_broadcasts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency broadcast",
                "verbose_name_plural": "Emergency broadcasts",
                "db_table": "radio_emergency_broadcast",
                "ordering": ["-priority", "-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "starts_at", "ends_at"],
                        name="radio_emerg_is_acti_326480_idx",
                    ),
                    models.Index(
                        fields=["priority", "-starts_at"],
                        name="radio_emerg_priorit_34ad7f_idx",
                    ),
                ],
            },
        ),
    ]
