# Generated by Django 5.1.15 on 2026-06-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0005_emergencybroadcast"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Free-form station description surfaced in detail views.",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="metadata_url",
            field=models.URLField(
                blank=True,
                help_text="Optional URL that exposes ICY / SHOUTcast metadata for the station's stream. Polled by ``radio.tasks.refresh_now_playing``.",
            ),
        ),
        migrations.CreateModel(
            name="NowPlaying",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_title", models.CharField(blank=True, max_length=500)),
                ("artist", models.CharField(blank=True, max_length=500)),
                ("album", models.CharField(blank=True, max_length=500)),
                ("artwork_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="now_playing",
                        to="radio.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Now playing",
                "verbose_name_plural": "Now playing",
                "db_table": "radio_now_playing",
            },
        ),
        migrations.CreateModel(
            name="StationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_listens", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="radio.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station analytics",
                "verbose_name_plural": "Station analytics",
                "db_table": "radio_station_analytics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["station", "-date"],
                        name="radio_stati_station_fb6126_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("station", "date"),
                        name="radio_station_analytics_station_date_unique",
                    )
                ],
            },
        ),
    ]
