# Generated by Django 5.1.15 on 2026-06-04 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0006_increase_area_ha_precision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("ndvi_decline", "NDVI decline"),
                            ("ndvi_low", "NDVI low absolute"),
                            ("activity_completed", "Activity completed"),
                            ("admin_broadcast", "Admin broadcast"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("ndvi_task", "NDVI task"),
                            ("activity_task", "Activity task"),
                            ("admin_view", "Admin view"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audio_alerts/%Y/%m/%d/",
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=64)),
                (
                    "source_object_id",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "is_delivered",
                    models.BooleanField(
                        default=False,
                        help_text="True once a WebSocket push has been confirmed.",
                    ),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="True once the user has marked the alert as read.",
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audio_alerts",
                        to="farms.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio alert",
                "verbose_name_plural": "Audio alerts",
                "db_table": "alerts_audio_alert",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="alerts_audi_user_id_0eb643_idx",
                    ),
                    models.Index(
                        fields=["user", "is_acknowledged"],
                        name="alerts_audi_user_id_5dbfa6_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "-created_at"],
                        name="alerts_audi_alert_t_690f8a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AudioAlertSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_types",
                    models.JSONField(
                        default=list,
                        help_text="List of AudioAlertType values the user wants to receive for this farm. An empty list means no alerts.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_alert_subscriptions",
                        to="farms.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_alert_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio alert subscription",
                "verbose_name_plural": "Audio alert subscriptions",
                "db_table": "alerts_audio_subscription",
                "indexes": [
                    models.Index(
                        fields=["user", "farm"],
                        name="alerts_audi_user_id_4bc1de_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "farm"),
                        name="alerts_audio_subscription_user_farm_unique",
                    )
                ],
            },
        ),
    ]
