# Generated by Django 5.1.15 on 2026-06-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioalert",
            name="client_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the client confirmed delivery via WebSocket ack.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="audioalert",
            name="delivery_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of WebSocket push attempts for this alert.",
            ),
        ),
        migrations.AddField(
            model_name="audioalert",
            name="last_delivery_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Last error message from WebSocket push, if any.",
            ),
        ),
        migrations.AlterField(
            model_name="audioalert",
            name="is_delivered",
            field=models.BooleanField(
                default=False,
                help_text="True once a WebSocket push has been confirmed by the server.",
            ),
        ),
    ]
