# Generated by Django 5.1.15 on 2026-02-22 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("event_type", models.CharField(max_length=120)),
                ("note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "created_by_client_id",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farm_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["farm", "observed_at"],
                        name="farms_farmo_farm_id_3ef246_idx",
                    )
                ],
            },
        ),
    ]
