# Generated by Django 5.1.15 on 2026-02-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_farmobservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmIntegrationAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_access",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client_id", "farm"],
                        name="farms_farmi_client__85df9e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("farm", "client_id"),
                        name="uniq_farm_integration_access",
                    )
                ],
            },
        ),
    ]
