# Generated by Django 5.1.15 on 2026-03-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_farmintegrationaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="external_farm_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="external_user_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
