# Generated by Django 5.1.15 on 2026-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_farm_external_farm_id_farm_external_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmSyncIdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=191, unique=True
                    ),
                ),
                ("external_farm_id", models.UUIDField(blank=True, null=True)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("response_payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"],
                        name="farms_farms_created_a64151_idx",
                    )
                ],
            },
        ),
    ]
