# Generated by Django 5.1.15 on 2026-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_farmsyncidempotencyrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="area_ha",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
    ]
