# Generated by Django 5.1.15 on 2026-01-30 16:13

import ndvi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ndvi",
            "0003_rename_ndvi_ndvir_owner_id_5f4203_idx_ndvi_ndvira_owner_i_adcf1f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ndviobservation",
            name="engine",
            field=models.CharField(
                default=ndvi.models.default_ndvi_engine_name, max_length=64
            ),
        ),
    ]
