# Generated by Django 5.1.15 on 2026-05-18 11:05

from django.db import migrations, models
from django.utils import timezone


def set_lifecycle_defaults(apps, schema_editor):
    NdviObservation = apps.get_model("ndvi", "NdviObservation")
    NdviObservation.objects.update(
        version="v1-legacy",
        state="FINAL",
        is_latest=True,
        computed_at=models.F("created_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0006_increase_area_ha_precision"),
        ("ndvi", "0004_alter_ndviobservation_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndviobservation",
            name="computed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ndviobservation",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ndviobservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("RAW", "Raw engine output before final acceptance"),
                    ("FINAL", "Data that passed cloud and quality checks"),
                ],
                default="FINAL",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ndviobservation",
            name="version",
            field=models.CharField(default="v1-legacy", max_length=32),
        ),
        migrations.RunPython(set_lifecycle_defaults, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="ndviobservation",
            index=models.Index(
                fields=["farm", "engine", "bucket_date", "is_latest"],
                name="ndvi_ndviob_farm_id_0d785f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ndviobservation",
            index=models.Index(
                fields=["version", "engine"],
                name="ndvi_ndviob_version_40b5c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ndviobservation",
            index=models.Index(
                fields=["state", "engine"], name="ndvi_ndviob_state_be95bc_idx"
            ),
        ),
    ]
