# Generated by Django 5.1.15 on 2026-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0006_increase_area_ha_precision"),
        ("ndvi", "0005_add_lifecycle_fields_to_observation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ndviobservation",
            name="uniq_ndvi_observation_farm_engine_bucket",
        ),
        migrations.AddConstraint(
            model_name="ndviobservation",
            constraint=models.UniqueConstraint(
                fields=("farm", "engine", "bucket_date", "version"),
                name="uniq_ndvi_observation_farm_engine_bucket_version",
            ),
        ),
    ]
