# Generated by Django 5.1.15 on 2026-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0006_increase_area_ha_precision"),
        ("ndvi", "0006_replace_observation_unique_constraint_for_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndviobservation",
            name="acquired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the satellite acquired the source scene",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ndviobservation",
            name="ingested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this row was persisted to the database",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ndviobservation",
            name="provenance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Processing inputs: engine version, SCL mask params, etc.",
            ),
        ),
        migrations.AddField(
            model_name="ndviobservation",
            name="source_scene_id",
            field=models.CharField(
                blank=True,
                help_text="Provider scene identifier for deduplication and provenance",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ndviobservation",
            name="computed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When NDVI was computed for this observation",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ndviobservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("RAW", "Raw engine output before final acceptance"),
                    ("FINAL", "Data that passed cloud and quality checks"),
                    ("SUPERSEDED", "Replaced by a newer observation"),
                ],
                default="FINAL",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="ndviobservation",
            index=models.Index(
                fields=["acquired_at", "engine"],
                name="ndvi_ndviob_acquire_31ffc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ndviobservation",
            index=models.Index(
                fields=["source_scene_id", "engine"],
                name="ndvi_ndviob_source__22eab2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ndviobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("farm", "engine", "bucket_date"),
                name="uniq_ndvi_latest_observation",
            ),
        ),
        migrations.AddConstraint(
            model_name="ndviobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_scene_id__isnull", False)),
                fields=("farm", "engine", "source_scene_id"),
                name="uniq_ndvi_scene_per_farm_engine",
            ),
        ),
    ]
