# Generated by Django 5.1.15 on 2026-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0006_increase_area_ha_precision"),
        ("ndvi", "0007_add_observation_hardening_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ndviobservation",
            name="uniq_ndvi_scene_per_farm_engine",
        ),
        migrations.AddField(
            model_name="ndviobservation",
            name="provenance_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Deterministic hash of provenance for idempotency",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ndviobservation",
            name="state",
            field=models.CharField(
                choices=[
                    ("RAW", "Raw engine output before final acceptance"),
                    ("FINAL", "Data that passed cloud and quality checks"),
                    ("SUPERSEDED", "Replaced by a newer observation"),
                    ("INVALIDATED", "Marked invalid due to bad source data"),
                    ("REJECTED", "Rejected by quality or processing rules"),
                ],
                default="FINAL",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="ndviobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_scene_id__isnull", False)),
                fields=(
                    "farm",
                    "engine",
                    "source_scene_id",
                    "provenance_hash",
                ),
                name="uniq_ndvi_scene_per_farm_engine",
            ),
        ),
    ]
