# Generated by Django 5.1.15 on 2026-05-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ndvi", "0010_ndviderivedobservation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ndviderivedobservation",
            new_name="ndvi_ndvide_farm_id_6e0bd3_idx",
            old_name="ndvi_ndvide_farm_id_6d3a46_idx",
        ),
        migrations.RenameIndex(
            model_name="ndviderivedobservation",
            new_name="ndvi_ndvide_engine_0968f7_idx",
            old_name="ndvi_ndvide_engine_1a5e3f_idx",
        ),
        migrations.RenameIndex(
            model_name="ndviderivedobservation",
            new_name="ndvi_ndvide_source_2c37ef_idx",
            old_name="ndvi_ndvide_source_8b2c1d_idx",
        ),
    ]
