# Generated by Django 5.1.15 on 2026-06-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ndvi",
            "0011_rename_ndvi_ndvide_farm_id_6d3a46_idx_ndvi_ndvide_farm_id_6e0bd3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ndviderivedobservation",
            name="index_type",
            field=models.CharField(
                choices=[("NDVI", "NDVI"), ("NDWI", "NDWI")],
                default="NDVI",
                help_text="Spectral index discriminator (NDVI, NDWI, etc.)",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ndvijob",
            name="index_type",
            field=models.CharField(
                choices=[("NDVI", "NDVI"), ("NDWI", "NDWI")],
                default="NDVI",
                help_text="Spectral index discriminator (NDVI, NDWI, etc.)",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ndviobservation",
            name="index_type",
            field=models.CharField(
                choices=[("NDVI", "NDVI"), ("NDWI", "NDWI")],
                db_index=True,
                default="NDVI",
                help_text="Spectral index discriminator (NDVI, NDWI, etc.)",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ndvirasterartifact",
            name="index_type",
            field=models.CharField(
                choices=[("NDVI", "NDVI"), ("NDWI", "NDWI")],
                default="NDVI",
                help_text="Spectral index discriminator (NDVI, NDWI, etc.)",
                max_length=16,
            ),
        ),
    ]
