# Generated by Django 5.1.15 on 2026-06-15 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_increase_area_ha_precision'),
        ('ndvi', '0012_add_index_type_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ndviderivedobservation',
            name='uniq_v2_farm_engine_bucket',
        ),
        migrations.RemoveConstraint(
            model_name='ndvijob',
            name='uniq_active_ndvi_job',
        ),
        migrations.RemoveConstraint(
            model_name='ndviobservation',
            name='uniq_ndvi_observation_farm_engine_bucket_version',
        ),
        migrations.RemoveConstraint(
            model_name='ndviobservation',
            name='uniq_ndvi_latest_observation',
        ),
        migrations.RemoveConstraint(
            model_name='ndviobservation',
            name='uniq_ndvi_scene_per_farm_engine',
        ),
        migrations.RemoveConstraint(
            model_name='ndvirasterartifact',
            name='uniq_ndvi_raster_farm_engine_date_size_cloud',
        ),
        migrations.RemoveIndex(
            model_name='ndviderivedobservation',
            name='ndvi_ndvide_farm_id_6e0bd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviderivedobservation',
            name='ndvi_ndvide_engine_0968f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviderivedobservation',
            name='ndvi_ndvide_source_2c37ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndvijob',
            name='ndvi_ndvijo_owner_i_df2efc_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndvijob',
            name='ndvi_ndvijo_request_98bc16_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviobservation',
            name='ndvi_ndviob_farm_id_c99de5_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviobservation',
            name='ndvi_ndviob_engine_9431d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviobservation',
            name='ndvi_ndviob_farm_id_0d785f_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviobservation',
            name='ndvi_ndviob_version_40b5c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviobservation',
            name='ndvi_ndviob_state_be95bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviobservation',
            name='ndvi_ndviob_acquire_31ffc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndviobservation',
            name='ndvi_ndviob_source__22eab2_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndvirasterartifact',
            name='ndvi_ndvira_owner_i_adcf1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='ndvirasterartifact',
            name='ndvi_ndvira_engine_f25a70_idx',
        ),
        migrations.AddIndex(
            model_name='ndviderivedobservation',
            index=models.Index(fields=['index_type', 'farm', 'engine', 'bucket_date'], name='ndvi_ndvide_index_t_3da265_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviderivedobservation',
            index=models.Index(fields=['index_type', 'engine', 'confidence'], name='ndvi_ndvide_index_t_135c12_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviderivedobservation',
            index=models.Index(fields=['index_type', 'source', 'bucket_date'], name='ndvi_ndvide_index_t_16bb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ndvijob',
            index=models.Index(fields=['index_type', 'owner', 'farm', 'status'], name='ndvi_ndvijo_index_t_d49931_idx'),
        ),
        migrations.AddIndex(
            model_name='ndvijob',
            index=models.Index(fields=['index_type', 'request_hash'], name='ndvi_ndvijo_index_t_38f1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviobservation',
            index=models.Index(fields=['index_type', 'farm', 'bucket_date'], name='ndvi_ndviob_index_t_bc6c50_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviobservation',
            index=models.Index(fields=['index_type', 'engine', 'bucket_date'], name='ndvi_ndviob_index_t_c1ebd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviobservation',
            index=models.Index(fields=['index_type', 'farm', 'engine', 'bucket_date', 'is_latest'], name='ndvi_ndviob_index_t_e4ea12_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviobservation',
            index=models.Index(fields=['index_type', 'version', 'engine'], name='ndvi_ndviob_index_t_db7f04_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviobservation',
            index=models.Index(fields=['index_type', 'state', 'engine'], name='ndvi_ndviob_index_t_c0eb66_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviobservation',
            index=models.Index(fields=['index_type', 'acquired_at', 'engine'], name='ndvi_ndviob_index_t_94bc31_idx'),
        ),
        migrations.AddIndex(
            model_name='ndviobservation',
            index=models.Index(fields=['index_type', 'source_scene_id', 'engine'], name='ndvi_ndviob_index_t_575caa_idx'),
        ),
        migrations.AddIndex(
            model_name='ndvirasterartifact',
            index=models.Index(fields=['index_type', 'owner_id', 'date'], name='ndvi_ndvira_index_t_89163c_idx'),
        ),
        migrations.AddIndex(
            model_name='ndvirasterartifact',
            index=models.Index(fields=['index_type', 'engine', 'date'], name='ndvi_ndvira_index_t_64e395_idx'),
        ),
        migrations.AddConstraint(
            model_name='ndviderivedobservation',
            constraint=models.UniqueConstraint(fields=('farm', 'engine', 'bucket_date', 'index_type'), name='uniq_v2_per_index_farm_engine_bucket'),
        ),
        migrations.AddConstraint(
            model_name='ndvijob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('owner', 'farm', 'engine', 'request_hash', 'index_type'), name='uniq_active_job_per_index'),
        ),
        migrations.AddConstraint(
            model_name='ndviobservation',
            constraint=models.UniqueConstraint(fields=('farm', 'engine', 'bucket_date', 'version', 'index_type'), name='uniq_observation_per_index_farm_engine_bucket_version'),
        ),
        migrations.AddConstraint(
            model_name='ndviobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('farm', 'engine', 'bucket_date', 'index_type'), name='uniq_observation_latest_per_index'),
        ),
        migrations.AddConstraint(
            model_name='ndviobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('source_scene_id__isnull', False)), fields=('farm', 'engine', 'source_scene_id', 'provenance_hash', 'index_type'), name='uniq_scene_per_index_farm_engine'),
        ),
        migrations.AddConstraint(
            model_name='ndvirasterartifact',
            constraint=models.UniqueConstraint(fields=('farm', 'engine', 'date', 'size', 'max_cloud', 'index_type'), name='uniq_raster_per_index_farm_engine_date_size_cloud'),
        ),
    ]
