# Generated by Django 5.1.15 on 2026-06-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndvi', '0013_remove_ndviderivedobservation_uniq_v2_farm_engine_bucket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndviderivedobservation',
            name='index_type',
            field=models.CharField(choices=[('NDVI', 'NDVI'), ('NDWI', 'NDWI'), ('NDMI', 'NDMI')], default='NDVI', help_text='Spectral index discriminator (NDVI, NDWI, NDMI, etc.)', max_length=16),
        ),
        migrations.AlterField(
            model_name='ndvijob',
            name='index_type',
            field=models.CharField(choices=[('NDVI', 'NDVI'), ('NDWI', 'NDWI'), ('NDMI', 'NDMI')], default='NDVI', help_text='Spectral index discriminator (NDVI, NDWI, NDMI, etc.)', max_length=16),
        ),
        migrations.AlterField(
            model_name='ndviobservation',
            name='index_type',
            field=models.CharField(choices=[('NDVI', 'NDVI'), ('NDWI', 'NDWI'), ('NDMI', 'NDMI')], db_index=True, default='NDVI', help_text='Spectral index discriminator (NDVI, NDWI, NDMI, etc.)', max_length=16),
        ),
        migrations.AlterField(
            model_name='ndvirasterartifact',
            name='index_type',
            field=models.CharField(choices=[('NDVI', 'NDVI'), ('NDWI', 'NDWI'), ('NDMI', 'NDMI')], default='NDVI', help_text='Spectral index discriminator (NDVI, NDWI, NDMI, etc.)', max_length=16),
        ),
    ]
