# Generated by Django 5.2.13 on 2026-06-28 07:40

import django.db.models.deletion
import ndvi.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_increase_area_ha_precision'),
        ('ndvi', '0014_alter_ndviderivedobservation_index_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNdviObservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('index_type', models.CharField(choices=[('NDVI', 'NDVI'), ('NDWI', 'NDWI'), ('NDMI', 'NDMI')], db_index=True, default='NDVI', help_text='Spectral index discriminator (NDVI, NDWI, NDMI, etc.)', max_length=16)),
                ('engine', models.CharField(default=ndvi.models.default_ndvi_engine_name, max_length=64)),
                ('bucket_date', models.DateField()),
                ('mean', models.FloatField()),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('sample_count', models.IntegerField(blank=True, null=True)),
                ('cloud_fraction', models.FloatField(blank=True, null=True)),
                ('valid_pixel_fraction', models.FloatField(blank=True, help_text='Fraction of pixels that passed SCL/quality masking', null=True)),
                ('quality_flags', models.JSONField(blank=True, default=dict, help_text='Quality indicators: cloud_heavy, partial_tile, low_valid_pixel_fraction, water_detected, etc.')),
                ('version', models.CharField(default='v1-legacy', max_length=32)),
                ('state', models.CharField(choices=[('RAW', 'Raw engine output before final acceptance'), ('FINAL', 'Data that passed cloud and quality checks'), ('SUPERSEDED', 'Replaced by a newer observation'), ('INVALIDATED', 'Marked invalid due to bad source data'), ('REJECTED', 'Rejected by quality or processing rules')], default='FINAL', max_length=16)),
                ('is_latest', models.BooleanField(default=True)),
                ('acquired_at', models.DateTimeField(blank=True, help_text='When the satellite acquired the source scene', null=True)),
                ('computed_at', models.DateTimeField(blank=True, help_text='When NDVI was computed for this observation', null=True)),
                ('ingested_at', models.DateTimeField(blank=True, help_text='When this row was persisted to the database', null=True)),
                ('source_scene_id', models.CharField(blank=True, help_text='Provider scene identifier for deduplication and provenance', max_length=256, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict, help_text='Processing inputs: engine version, SCL mask params, etc.')),
                ('provenance_hash', models.CharField(blank=True, db_index=True, help_text='Deterministic hash of provenance for idempotency', max_length=64, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('farm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='farms.farm')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ndvi observation',
                'verbose_name_plural': 'historical ndvi observations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
