# Generated by Django 5.2.13 on 2026-07-01 15:02

from django.db import migrations, models

HELP = "Spectral index discriminator (NDVI, NDWI, NDMI, etc.)"


class Migration(migrations.Migration):
    dependencies = [
        ("ndvi", "0015_historicalndviobservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalndviobservation",
            name="index_type",
            field=models.CharField(
                choices=[
                    ("NDVI", "NDVI"),
                    ("NDWI", "NDWI"),
                    ("NDMI", "NDMI"),
                    ("RVI", "RVI"),
                    ("S1_SMI", "S1_SMI"),
                ],
                db_index=True,
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ndviderivedobservation",
            name="index_type",
            field=models.CharField(
                choices=[
                    ("NDVI", "NDVI"),
                    ("NDWI", "NDWI"),
                    ("NDMI", "NDMI"),
                    ("RVI", "RVI"),
                    ("S1_SMI", "S1_SMI"),
                ],
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ndvijob",
            name="index_type",
            field=models.CharField(
                choices=[
                    ("NDVI", "NDVI"),
                    ("NDWI", "NDWI"),
                    ("NDMI", "NDMI"),
                    ("RVI", "RVI"),
                    ("S1_SMI", "S1_SMI"),
                ],
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ndviobservation",
            name="index_type",
            field=models.CharField(
                choices=[
                    ("NDVI", "NDVI"),
                    ("NDWI", "NDWI"),
                    ("NDMI", "NDMI"),
                    ("RVI", "RVI"),
                    ("S1_SMI", "S1_SMI"),
                ],
                db_index=True,
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ndvirasterartifact",
            name="index_type",
            field=models.CharField(
                choices=[
                    ("NDVI", "NDVI"),
                    ("NDWI", "NDWI"),
                    ("NDMI", "NDMI"),
                    ("RVI", "RVI"),
                    ("S1_SMI", "S1_SMI"),
                ],
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
    ]
