# Generated by Django 5.2.13 on 2026-07-01 20:26

from django.db import migrations, models

HELP = "Spectral index discriminator (NDVI, NDWI, NDMI, etc.)"

CHOICES = [
    ("NDVI", "NDVI"),
    ("NDWI", "NDWI"),
    ("NDMI", "NDMI"),
    ("RVI", "Radar Vegetation Index"),
    ("S1_SMI", "Sentinel-1 Soil Moisture Index"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("ndvi", "0016_add_sar_index_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalndviobservation",
            name="index_type",
            field=models.CharField(
                choices=CHOICES,
                db_index=True,
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ndviderivedobservation",
            name="index_type",
            field=models.CharField(
                choices=CHOICES,
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ndvijob",
            name="index_type",
            field=models.CharField(
                choices=CHOICES,
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ndviobservation",
            name="index_type",
            field=models.CharField(
                choices=CHOICES,
                db_index=True,
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="ndvirasterartifact",
            name="index_type",
            field=models.CharField(
                choices=CHOICES,
                default="NDVI",
                help_text=HELP,
                max_length=16,
            ),
        ),
    ]
