from __future__ import annotations

from django.urls import path
from django.views.generic import RedirectView

from .proxy_views import NdviIngestProxyView
from .views import (
    CircuitBreakerResetView,
    FarmStateView,
    NdmiFarmStateView,
    NdmiLatestView,
    NdmiRasterPngView,
    NdmiRasterQueueView,
    NdmiRefreshView,
    NdmiTimeseriesView,
    NdviJobStatusView,
    NdviLatestView,
    NdviRasterPngView,
    NdviRasterQueueView,
    NdviRefreshView,
    NdviTimeseriesView,
    NdwiFarmStateView,
    NdwiLatestView,
    NdwiRasterPngView,
    NdwiRasterQueueView,
    NdwiRefreshView,
    NdwiTimeseriesView,
    UpstreamHealthView,
)

urlpatterns = [
    path(
        "farm-state/",
        RedirectView.as_view(url="/api/v1/farms/", permanent=True),
        name="farm-state-redirect",
    ),
    path(
        "farm-state/<int:farm_id>/",
        FarmStateView.as_view(),
        name="farm-state",
    ),
    path(
        "farms/<int:farm_id>/ndvi/timeseries/",
        NdviTimeseriesView.as_view(),
        name="ndvi-timeseries",
    ),
    path(
        "farms/<int:farm_id>/ndvi/latest/",
        NdviLatestView.as_view(),
        name="ndvi-latest",
    ),
    path(
        "farms/<int:farm_id>/ndvi/refresh/",
        NdviRefreshView.as_view(),
        name="ndvi-refresh",
    ),
    path(
        "farms/<int:farm_id>/ndvi/raster.png",
        NdviRasterPngView.as_view(),
        name="ndvi-raster",
    ),
    path(
        "farms/<int:farm_id>/ndvi/raster/queue",
        NdviRasterQueueView.as_view(),
        name="ndvi-raster-queue",
    ),
    path(
        "ndvi/jobs/<int:job_id>/",
        NdviJobStatusView.as_view(),
        name="ndvi-job",
    ),
    path(
        "ndvi",
        NdviIngestProxyView.as_view(),
        name="ndvi-ingest",
    ),
    path(
        "ndvi/circuit-breaker/reset/",
        CircuitBreakerResetView.as_view(),
        name="ndvi-circuit-breaker-reset",
    ),
    path(
        "ndvi/health/upstream/",
        UpstreamHealthView.as_view(),
        name="ndvi-health-upstream",
    ),
    # ── NDWI endpoints ─────────────────────────────────────────
    path(
        "farms/<int:farm_id>/ndwi/timeseries/",
        NdwiTimeseriesView.as_view(),
        name="ndwi-timeseries",
    ),
    path(
        "farms/<int:farm_id>/ndwi/latest/",
        NdwiLatestView.as_view(),
        name="ndwi-latest",
    ),
    path(
        "farms/<int:farm_id>/ndwi/refresh/",
        NdwiRefreshView.as_view(),
        name="ndwi-refresh",
    ),
    path(
        "farms/<int:farm_id>/ndwi/raster.png",
        NdwiRasterPngView.as_view(),
        name="ndwi-raster",
    ),
    path(
        "farms/<int:farm_id>/ndwi/raster/queue",
        NdwiRasterQueueView.as_view(),
        name="ndwi-raster-queue",
    ),
    path(
        "farms/<int:farm_id>/ndwi/farm-state/",
        NdwiFarmStateView.as_view(),
        name="ndwi-farm-state",
    ),
    # ── NDMI endpoints ─────────────────────────────────────────
    path(
        "farms/<int:farm_id>/ndmi/timeseries/",
        NdmiTimeseriesView.as_view(),
        name="ndmi-timeseries",
    ),
    path(
        "farms/<int:farm_id>/ndmi/latest/",
        NdmiLatestView.as_view(),
        name="ndmi-latest",
    ),
    path(
        "farms/<int:farm_id>/ndmi/refresh/",
        NdmiRefreshView.as_view(),
        name="ndmi-refresh",
    ),
    path(
        "farms/<int:farm_id>/ndmi/raster.png",
        NdmiRasterPngView.as_view(),
        name="ndmi-raster",
    ),
    path(
        "farms/<int:farm_id>/ndmi/raster/queue",
        NdmiRasterQueueView.as_view(),
        name="ndmi-raster-queue",
    ),
    path(
        "farms/<int:farm_id>/ndmi/farm-state/",
        NdmiFarmStateView.as_view(),
        name="ndmi-farm-state",
    ),
]
